export const APPLICATION_READY = 'APPLICATION_READY';
export const ADD_TO_QUEUE = 'ADD_TO_QUEUE';

export const RECEIVE_TRACKS    = 'RECEIVE_TRACKS';
export const RECEIVE_GREETINGS = 'RECEIVE_GREETINGS';
export const PLAY_TRACK        = 'PLAY_TRACK';
export const PLAY_TRACK_NEXT   = 'PLAY_TRACK_NEXT';
export const PLAY_TRACK_PREV   = 'PLAY_TRACK_PREV';
export const PAUSE_TRACK       = 'PAUSE_TRACK';

export const RECEIVE_ARTISTS = 'RECEIVE_ARTISTS';
