export const APPLICATION_READY = 'APPLICATION_READY';
export const ADD_TO_QUEUE = 'ADD_TO_QUEUE';

export const RECEIVE_TRACKS    = 'RECEIVE_TRACKS';
export const RECEIVE_GREETINGS = 'RECEIVE_GREETINGS';
export const PLAY_TRACK        = 'PLAY_TRACK';
export const PLAY_TRACK_NEXT   = 'PLAY_TRACK_NEXT';
export const PLAY_TRACK_PREV   = 'PLAY_TRACK_PREV';
export const PAUSE_TRACK       = 'PAUSE_TRACK';

export const USER_LOGGED_IN = "USER_LOGGED_IN";
export const USER_OFFLINE = "USER_OFFLINE";

export const LOG_EVENT = "LOG_EVENT";

export const SET_PLAYING_STATUS = 'SET_PLAYING_STATUS';
export const SET_MUSIC_DURATION = 'SET_MUSIC_DURATION';
export const SET_MUSIC_RIGHTNOW = 'SET_MUSIC_RIGHTNOW';
export const SET_CURRENT_MUSIC  = 'SET_CURRENT_MUSIC';
export const SET_LOADING_STATUS = 'SET_LOADING_STATUS';

export const RECEIVE_ARTISTS = 'RECEIVE_ARTISTS';
